plataforma/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('quem_somos', views.equipe_fatec, name='quem_somos'),
]
urlpatterns_aluno = [
    path('index_aluno', views.index_aluno, name='core_index_aluno'),
    path('cadastro_novo_aluno', views.cadastro_novo_aluno, name='cadastro_novo_aluno'),
]

urlpatterns_professor = [
    path('index_professor', views.index_professor, name='core_index_professor'),
    path('perfil_professor', views.perfil_professor, name='perfil_professor'),
]
urlpatterns_empresa = [
    path('index_empresa', views.index_empresa, name='core_index_empresa'),
]
urlpatterns_manutencao = [
    path('index_manutencao', views.index_manutencao, name='core_index_manutencao'),
]
urlpatterns += urlpatterns_aluno
urlpatterns += urlpatterns_empresa
urlpatterns += urlpatterns_professor
urlpatterns += urlpatterns_manutencao

plataforma/plataforma/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from plataforma import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('vitrine.urls')),
    path('manutencao/', include('manutencao.urls')),
    path('estagio/', include('estagio.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plataforma/vitrine/urls.py
from django.urls import path, re_path
from . import views

app_name = 'vitrine'

urlpatterns = [
    path('', views.showcase, name='showcase'),
    path('cadastro', views.cadastro, name='cadastro'),
    path('remover', views.remover, name='remover'),
    path('curso/<int:curso>', views.showcase_tipo_curso, name='showcase_tipo_curso'),
    path('tipo/<int:tipo_vaga>', views.showcase_tipo_vaga, name='showcase_tipo_vaga'),
    path('api/vitrine/', views.VitrineList.as_view(), name='vitrine-list'),
    re_path('^api/vitrine/tipo/(?P<tipo>.*)/$', views.VitrineListVaga.as_view(), name='vitrine-list-vaga'),
]

plataforma/vitrine/models.py
from datetime import timedelta
from django.db import models
from django.db.models import Q
from django.utils import timezone
from core.models import CURSO_FATEC, User


TIPO_VAGA = (
    ('0', 'Emprego'),
    ('1', 'Estágio'),
    ('2', 'Emprego ou Estágio'),
)


class VitrineManager(models.Manager):
    def get_alunos(self):
        one_month_ago = timezone.now() - timedelta(days=30)
        return VitrineModel.objects.filter(
            updated_at__gte=one_month_ago
        ).order_by('updated_at')
    
    def get_alunos_emprego(self):
        alunos = self.get_alunos()
        return alunos.filter(Q(tipo_vaga=0) | Q(tipo_vaga=2))

    def get_alunos_estagio(self):
        alunos = self.get_alunos()
        return alunos.filter(Q(tipo_vaga=1) | Q(tipo_vaga=2))

    def get_tipo_vaga(self, tipo_vaga):
        alunos = self.get_alunos()
        return alunos.filter(Q(tipo_vaga=tipo_vaga) | Q(tipo_vaga=2))
    
    def get_tipo_curso(self, curso):
        alunos = self.get_alunos()
        return alunos.filter(curso=curso)


class VitrineModel(models.Model):
    aluno = models.ForeignKey(User, on_delete=models.CASCADE)
    descricao = models.TextField()
    linkedin = models.URLField(default='', blank=True)
    github = models.URLField(default='', blank=True)
    curso = models.CharField(
        verbose_name='Curso Matriculado',
        max_length=2,
        choices=CURSO_FATEC,
        default='0'
    )
    tipo_vaga = models.CharField(
        verbose_name='Tipo da Vaga',
        max_length=2,
        choices=TIPO_VAGA,
        default='2'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = VitrineManager()

    class Meta:
        verbose_name_plural = 'Alunos cadastrados'
        verbose_name = 'Aluno cadastrado'
    
    def __str__(self):
        return f'{self.aluno.first_name} - {self.aluno.email}'

plataforma/vitrine/forms.py
from django.core.exceptions import ValidationError
from django import forms
from django.forms import ModelForm
from vitrine.models import VitrineModel
from django.core.exceptions import ValidationError


class VitrineForm(ModelForm):
    class Meta:
        model = VitrineModel
        fields = ('aluno', 'curso', 'tipo_vaga', 'descricao',
                  'linkedin', 'github')
        labels = {
            'aluno': 'Nome',
            'descricao': 'Descricao',
            'linkedin': 'Link Linkedin',
            'github': 'Link Github',
            'curso': 'Curso',
            'tipo_vaga': 'Tipo da Vaga'
        }
        widgets = {
            'aluno': forms.HiddenInput(attrs={'class': 'form-control'}),
            'curso': forms.Select(attrs={'class': 'form-control'}),
            'tipo_vaga': forms.Select(attrs={'class': 'form-control'}),
            'descricao': forms.Textarea(attrs={'class': 'form-control'}),
            'linkedin': forms.URLInput(attrs={'class': 'form-control'}),
            'github': forms.URLInput(attrs={'class': 'form-control'}),
        }
        error_messages = {
            'descricao': {
                'required': ("Você precisa nos contar algo sobre você."),
            },
            'linkedin': {
                'required': ("Você precisa colocar seu endereço do Linkedin"),
            }
        }

    def clean(self):
        self.cleaned_data = super().clean()
        sem_linkein = not self.cleaned_data.get('linkedin')
        sem_github = not self.cleaned_data.get('github')
        if sem_linkein and sem_github:
            raise ValidationError('Informe ao menos uma rede social.')
        return self.cleaned_data

plataforma/vitrine/views.py
from django.shortcuts import render, redirect
from core.decorators import area_student
from vitrine.forms import VitrineForm
from vitrine.models import VitrineModel
from rest_framework import generics
from .serializers import VitrineSerializer
from django.http import Http404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

from django_filters.rest_framework import DjangoFilterBackend


def showcase(request):
    alunos = VitrineModel.objects.get_alunos()
    return render(request, 'showcase.html', {'alunos': alunos})


def showcase_tipo_vaga(request, tipo_vaga):
    alunos = VitrineModel.objects.get_tipo_vaga(tipo_vaga)
    return render(request, 'showcase.html', {'alunos': alunos})


def showcase_tipo_curso(request, curso):
    alunos = VitrineModel.objects.get_tipo_curso(curso)
    return render(request, 'showcase.html', {'alunos': alunos})


@area_student
def cadastro(request):
    if request.method == 'GET':
        context = {'cabecalho': 'Plataforma FATEC - Módulo Vitrine',
            'form': VitrineForm(), 'user': request.user}
        return render(request, 'cadastro.html', context)
    else:
        form = VitrineForm(request.POST)
        if form.is_valid():
            VitrineModel.objects.filter(aluno_id=request.user.pk).delete()
            VitrineModel.objects.create(**form.cleaned_data)
            context = {'cabecalho': 'Plataforma FATEC - Módulo Vitrine',
                       'mensagem': 'Cadastro feito com sucesso'} 
            return render(request, 'cadastro_feito.html', context)
        else:
            context = {'form': form, 'user': request.user}
            return render(request, 'cadastro.html', context)


@area_student
def remover(request):
    if request.method == 'GET':
        cadastro = VitrineModel.objects.filter(aluno_id=request.user.pk)
        if cadastro:
            context = {'cadastro': cadastro[0],
                       'user': request.user}
            return render(request, 'remover.html', context)
        else:
            context = {'cabecalho': 'Você não possui registro ainda',
                       'form': VitrineForm(), 'user': request.user}
            return render(request, 'cadastro.html', context)
    else:
        VitrineModel.objects.filter(aluno_id=request.user.pk).delete()
        context = {'cabecalho': 'Plataforma FATEC - Módulo Vitrine',
                   'mensagem': 'Seu anúncio foi removido.'} 
        return render(request, 'cadastro_feito.html', context)

# API views here.
class VitrineList(generics.ListAPIView):
    
    queryset = VitrineModel.objects.get_alunos()
    serializer_class = VitrineSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['tipo_vaga']

class VitrineListVaga(generics.ListAPIView):
    
    # queryset = VitrineModel.objects.get_alunos()
    serializer_class = VitrineSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['tipo_vaga']
    def get_queryset(self):
        tipo = self.kwargs['tipo']
        queryset = VitrineModel.objects.get_tipo_vaga(tipo)
        return queryset

plataforma/vitrine/templates/cadastro.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}


{% block content %}

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    {% include "aluno_sidebar.html" %}
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        {% include "aluno_topbar.html" %}
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">{{ cabecalho }}</h1>
          </div>
        </div>
      </div>

      <div class="container">
        {% if form.errors %}
          <div class="row">
            {% for field in form %}
              {% if field.errors %}
                <div class="col-xl-6 col-md-12 mb-4">
                  <div class="card border-left-danger shadow h-100 py-2">
                    <div class="card-body">
                      <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                              <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                {% for error in field.errors %}
                                  <strong>{{ error|escape }}</strong>
                                {% endfor %}
                              </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              {% endif %}
            {% endfor %}
          </div>
        {% endif %}
        {% if form.non_field_errors  %}
          <div class="row">}
            <div class="col-xl-6 col-md-12 mb-4">
              <div class="card border-left-danger shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                        {% for error in form.non_field_errors %}
                          <strong>{{ error|escape }}</strong>
                        {% endfor %}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endif %}
        <!-- Content Row -->
        <div class="row">

          <!-- Dados em um card -->
          <div class="col-xl-6 col-md-12 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
              <div class="card-body">
                <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                    <form action="{% url 'vitrine:cadastro' %}" novalidate method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type='hidden' name='aluno' value = "{{user.pk }}"/>
                        {% for field in form %}
                          {% if field.label != 'Nome' %}
                            {{ field.label_tag }}
                            {{ field }}
                          {% endif %}
                        {% endfor %}
                        <input type="submit" value="Cadastrar"/>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    {% include "rodape.html" %}
    </div>
  </div>
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>
{% endblock %}

plataforma/vitrine/templates/cadastro_feito.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}


{% block content %}

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    {% include "aluno_sidebar.html" %}
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        {% include "aluno_topbar.html" %}
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">{{ cabecalho }}</h1>
          </div>
      


          <!-- Content Row -->
          <div class="row">

            <div class="col-xl-6 col-md-12 mb-4">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="h5 mb-0 font-weight-bold text-gray-800">
                        <a href="{% url 'core:home' %}">{{ mensagem }}</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>

          </div>


    {% include "rodape.html" %}
    </div>
  </div>
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>
{% endblock %}

plataforma/vitrine/templates/remover.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}


{% block content %}

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    {% include "aluno_sidebar.html" %}
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        {% include "aluno_topbar.html" %}
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Plataforma FATEC - Módulo Vitrine</h1>
          </div>
      


          <!-- Content Row -->
          <div class="row">
            <div class="col-xl-6 col-md-12 mb-4">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <form action={% url 'vitrine:remover' %} novalidate method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type='hidden' name='aluno' value = "{{user.pk }}"/>
            
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="h5 mb-0 font-weight-bold text-gray-800">
                        <a href="{% url 'core:home' %}">Não desejo remover meu cadastro</a>
                      </div>
                      <b>Descrição:</b><br>
                      {{ cadastro.descricao }}
                      <br>
                      <b>LinkedIn</b><br>
                      {{ cadastro.linkedin }}
                      <b>GitHub</b><br>
                      {{ cadastro.github }}
                      <br>
                    </div>
                  </div>
                  <input type="submit" value="Remover"/>
                </form>
                </div>
              </div>
            </div>
        </div>

          </div>


    {% include "rodape.html" %}
    </div>
  </div>
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>
{% endblock %}

plataforma/vitrine/templates/showcase.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}


{% block content %}

 <!-- Page Wrapper -->
 <div id="wrapper">

    <!-- Sidebar -->
    {% include "vitrine_sidebar.html" %}
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        {% include "vitrine_topbar.html" %}
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container">
            
              {% if alunos %}
                {% for aluno in alunos %}
                  <div class="col">
                    <div class="card border-left-primary shadow mb-4 h">
                      <div class="card-body">
                        <div class="row no-gutters align-items-center">
                          <div class="col mr-2">
                            <h3 class="card-title">{{ aluno.get_tipo_vaga_display }}</h3>
                            <hr/>
                            <h5>{{ aluno.aluno.first_name }} {{ aluno.aluno.last_name }}</h5>
                            <h5>Curso: {{ aluno.get_curso_display }}</h5>
                            <p class="card-text mt-3">{{ aluno.descricao }}</p>
                            <div class="collapse" id="collapse_{{ aluno.pk }}">
                              <div class="container p-0 d-inline-flex mb-3">
                                <div class="row">
                                  {% if aluno.linkedin %}
                                    <div class="col-md">
                                      <a href="{{ aluno.linkedin }}" target="_blank">
                                        <div class="d-inline-flex">
                                          <h3 class="m-0"><i class="fab fa-linkedin"></i></h3>
                                          <span class="mt-1 ml-2">Linkedin</span>
                                        </div>
                                      </a>
                                    </div>
                                  {% endif %}

                                  {% if aluno.github %}
                                    <div class="col-md">
                                      <a href="{{ aluno.github }}" target="_blank">
                                        <div class="d-inline-flex">
                                          <h3 class="m-0"><i class="fab fa-github"></i></h3>
                                          <span class="mt-1 ml-2">Github</span>
                                        </div>
                                      </a>
                                    </div>
                                  {% endif %}
                                  </div>
                              </div>
                            </div>
                            <button class="btn btn-primary" type="button" 
                              data-toggle="collapse" data-target="#collapse_{{aluno.pk}}" 
                                aria-expanded="false" aria-controls="collapse">
                                Ver mais
                            </button>
                          </div>
                        </div>
                      </div>  
                    </div>
                  </div>
                {% endfor %}
              {% else %}
                  <div class="container">
                    <h1>Nenhum resultado encontrado!</h1>
                  </div>
              {% endif %}
            
          </div>
    </div>
        {% include "rodape.html" %}
    </div>
  </div>
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>
{% endblock %}

plataforma/vitrine/templates/vitrine_sidebar.html
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'vitrine:showcase' %}">
          <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
          </div>
          <div class="sidebar-brand-text mx-3">Nossos talentos</div>
        </a>
  
        <!-- Divider -->
        <hr class="sidebar-divider my-0">
  
        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'core:home' %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Acesso a Plataforma</span></a>
        </li>
  
        <!-- Divider -->
        <hr class="sidebar-divider">
  
        <!-- Heading -->
        <div class="sidebar-heading">
          Filtros
        </div>
  
        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
          <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cog"></i>
            <span>Cursos</span>
          </a>
          <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
              <a class="collapse-item" href="{% url 'vitrine:showcase_tipo_curso' 0 %}">Sistemas para Internet</a>
              <a class="collapse-item" href="{% url 'vitrine:showcase_tipo_curso' 1 %}">Gestão Empresarial</a>
            </div>
          </div>
        </li>



        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsethree" aria-expanded="true" aria-controls="collapsethree">
              <i class="fas fa-fw fa-cog"></i>
              <span>Tipos de vagas</span>
            </a>
            <div id="collapsethree" class="collapse" aria-labelledby="headingthree" data-parent="#accordionSidebar">
              <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{% url 'vitrine:showcase_tipo_vaga' 0 %}">Emprego</a>
                <a class="collapse-item" href="{% url 'vitrine:showcase_tipo_vaga' 1 %}">Estágio</a>
              </div>
            </div>
          </li>
  
        
        
  
        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">
  
        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
          <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>
  
      </ul>
      <!-- End of Sidebar -->

plataforma/vitrine/templates/vitrine_topbar.html
        {% load static %}
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <div class="container-fluid">

            <div class="m-4">
              <h1 class="h3 mb-0 text-gray-800 text-center"> Plataforma FATEC ARARAS</h1>
            </div>
          </div>

        </nav>