plataforma/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('quem_somos', views.equipe_fatec, name='quem_somos'),
]
urlpatterns_aluno = [
    path('index_aluno', views.index_aluno, name='core_index_aluno'),
    path('cadastro_novo_aluno', views.cadastro_novo_aluno, name='cadastro_novo_aluno'),
]

urlpatterns_professor = [
    path('index_professor', views.index_professor, name='core_index_professor'),
    path('perfil_professor', views.perfil_professor, name='perfil_professor'),
]
urlpatterns_empresa = [
    path('index_empresa', views.index_empresa, name='core_index_empresa'),
]
urlpatterns_manutencao = [
    path('index_manutencao', views.index_manutencao, name='core_index_manutencao'),
]
urlpatterns += urlpatterns_aluno
urlpatterns += urlpatterns_empresa
urlpatterns += urlpatterns_professor
urlpatterns += urlpatterns_manutencao

plataforma/estagio/urls.py
from django.urls import path
from . import views

app_name = 'estagio'

urlpatterns = []

urlpatterns_empresa = [
    path('upload_convenio', views.upload_convenio,
         name='upload_convenio'),
    path('upload_documentos_estagio', views.upload_documentos_estagio,
         name='upload_documentos_estagio'),
    path('convenio_por_empresa', views.convenio_por_empresa,
         name='convenio_por_empresa'),
    path('estagiarios_por_empresa', views.estagiarios_por_empresa,
         name='estagiarios_por_empresa'),
]
urlpatterns_professor = [
     path('professor_upload_documentos_estagio',
         views.professor_upload_documentos_estagio,
         name='professor_upload_documentos_estagio'),
     path('professor_upload_convenio', views.professor_upload_convenio,
         name='professor_upload_convenio'),
     path('pre_validar_convenio', views.pre_validar_convenio,
         name='pre_validar_convenio'),
     path('validar_convenio', views.validar_convenio,
         name='validar_convenio'),
     path('pos_validar_convenio', views.pos_validar_convenio,
         name='pos_validar_convenio'),
     path('listar_todos_convenios', views.listar_todos_convenios,
         name='listar_todos_convenios'),
     path('pre_validar_documento_estagio', views.pre_validar_documento_estagio,
         name='pre_validar_documento_estagio'),
     path('validar_documento_estagio', views.validar_documento_estagio,
         name='validar_documento_estagio'),
     path('pos_validar_documento_estagio', views.pos_validar_documento_estagio,
         name='pos_validar_documento_estagio'),
     path('listar_termos_compromisso_estagio',
          views.listar_termos_compromisso_estagio,
         name='listar_termos_compromisso_estagio'),
     path('listar_planos_de_atividades', views.listar_planos_de_atividades,
         name='listar_planos_de_atividades'),
     path('listar_termo_aditivo', views.listar_termo_aditivo,
         name='listar_termo_aditivo'),
     path('listar_rescisao_de_contrato', views.listar_rescisao_de_contrato,
         name='listar_rescisao_de_contrato'),
     path('listar_ficha_avaliacao_estagiario', views.listar_ficha_avaliacao_estagiario,
         name='listar_ficha_avaliacao_estagiario'),
     path('listar_relatorio_parcial_estagio', views.listar_relatorio_parcial_estagio,
         name='listar_relatorio_parcial_estagio'),
     path('listar_relatorio_final_estagio', views.listar_relatorio_final_estagio,
         name='listar_relatorio_final_estagio'),
]
urlpatterns += urlpatterns_empresa
urlpatterns += urlpatterns_professor

plataforma/plataforma/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from plataforma import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('vitrine.urls')),
    path('manutencao/', include('manutencao.urls')),
    path('estagio/', include('estagio.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plataforma/estagio/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse as r
from core.facade import area_trainee_coordinador, area_teacher, area_company
from estagio.forms import ConvenioForm, DocumentoEstagioForm
from estagio.forms import ProfessorConvenioForm, ProfessorDocumentoEstagioForm
from estagio.models import ConvenioModel, DocumentoEstagioModel
from plataforma import settings


@area_teacher
def listar_todos_convenios(request):
    convenios = ConvenioModel.objects.all().order_by('-created_at')
    context = {'media_url': settings.MEDIA_URL,
               'convenios': convenios}
    return render(request, 'listar_convenios.html', context)


@area_teacher
def pre_validar_convenio(request):
    if request.method == 'GET':
        convenios = ConvenioModel.objects.filter(observacao_professor='')
        context = {'media_url': settings.MEDIA_URL,
                   'convenios': convenios}
        return render(request, 'pre_validar_convenio.html', context)
    else:
        return HttpResponseRedirect(r('core:core_index_professor'))


@area_trainee_coordinador
def validar_convenio(request):
    if request.method == 'GET':
        return HttpResponseRedirect(r('core:core_index_professor'))
    else:
        id = request.POST.get('convenio_id', '')
        if id != '':
            convenio = ConvenioModel.objects.filter(pk=id)[0]
            context = {'media_url': settings.MEDIA_URL,
                       'convenio': convenio}
            return render(request, 'validar_convenio.html', context)
        else:
            return HttpResponseRedirect(r('core:core_index_professor'))


@area_trainee_coordinador
def pos_validar_convenio(request):
    if request.method == 'GET':
        return HttpResponseRedirect(r('core:core_index_professor'))
    else:
        id = request.POST.get('convenio_id', '')
        obs_padrao = 'Parecer Emitido pelo docente.'
        observacao = request.POST.get('observacao_professor', obs_padrao)
        aprovado = request.POST.get('aprovado_reprovado', '1')
        convenio = ConvenioModel.objects.filter(pk=id)[0]
        convenio.observacao_professor = observacao
        convenio.aprovado_professor = aprovado
        convenio.save()
        return render(request, 'pos_validar_convenio.html')


@area_teacher
def pre_validar_documento_estagio(request):
    if request.method == 'GET':
        documentos = DocumentoEstagioModel.objects.filter(
            observacao_professor='')
        context = {'media_url': settings.MEDIA_URL,
                   'documentos': documentos}
        return render(request, 'pre_validar_documento_estagio.html', context)
    else:
        return HttpResponseRedirect(r('core:core_index_professor'))


@area_trainee_coordinador
def professor_upload_convenio(request):
    if request.method == 'GET':
        context = {'form': ProfessorConvenioForm()}
        return render(request, 'professor_upload_convenio.html', context)
    else:
        form = ProfessorConvenioForm(request.POST, request.FILES)
        if form.is_valid():
            novo_nome = form.renomear_arquivo(form.files['documento'].name)
            form.files['documento'].name = novo_nome
            ConvenioModel.objects.create(**form.cleaned_data)
            return render(request, 'arquivo_enviado_pelo_professor.html')
        else:
            context = {'form': form}
            return render(request, 'professor_upload_convenio.html', context)


@area_trainee_coordinador
def professor_upload_documentos_estagio(request):
    if request.method == 'GET':
        context = {'form': ProfessorDocumentoEstagioForm()}
        return render(request, 'professor_upload_documentos_estagio.html', context)
    else:
        form = ProfessorDocumentoEstagioForm(request.POST, request.FILES)
        if form.is_valid():
            novo_nome = form.renomear_arquivo(form.files['documento'].name)
            form.files['documento'].name = novo_nome
            DocumentoEstagioModel.objects.create(**form.cleaned_data)
            return render(request, 'arquivo_enviado_pelo_professor.html')
        else:
            context = {'form': form}
            return render(request, 'professor_upload_documentos_estagio.html', context)



@area_trainee_coordinador
def validar_documento_estagio(request):
    if request.method == 'GET':
        return HttpResponseRedirect(r('core:core_index_professor'))
    else:
        id = request.POST.get('documento_id', '')
        if id != '':
            documento = DocumentoEstagioModel.objects.filter(pk=id)[0]
            context = {'media_url': settings.MEDIA_URL,
                       'documento': documento}
            return render(request, 'validar_documento_estagio.html', context)
        else:
            return HttpResponseRedirect(r('core:core_index_professor'))


@area_trainee_coordinador
def pos_validar_documento_estagio(request):
    if request.method == 'GET':
        return HttpResponseRedirect(r('core:core_index_professor'))
    else:
        id = request.POST.get('documento_id', '')
        if id != '':
            obs_padrao = 'Parecer Emitido pelo docente.'
            observacao = request.POST.get('observacao_professor', obs_padrao)
            aprovado = request.POST.get('aprovado_reprovado', '1')
            documento = DocumentoEstagioModel.objects.filter(pk=id)[0]
            documento.observacao_professor = observacao
            documento.aprovado_professor = aprovado
            documento.save()
            return render(request, 'pos_validar_documento_estagio.html')
        else:
            return HttpResponseRedirect(r('core:core_index_professor'))


@area_company
def upload_convenio(request):
    if request.method == 'GET':
        context = {'form': ConvenioForm(
            initial={"empresa": request.user.pk})}
        return render(request, 'upload_convenio.html', context)
    else:
        form = ConvenioForm(request.POST, request.FILES)
        if form.is_valid():
            novo_nome = form.renomear_arquivo(form.files['documento'].name)
            form.files['documento'].name = novo_nome
            ConvenioModel.objects.create(**form.cleaned_data)
            return render(request, 'arquivo_enviado_com_sucesso.html')
        else:
            context = {'form': form}
            return render(request, 'upload_convenio.html', context)


@area_company
def upload_documentos_estagio(request):
    if request.method == 'GET':
        context = {'form': DocumentoEstagioForm(
            initial={"empresa": request.user.pk})}
        return render(request, 'upload_documentos_estagio.html', context)
    else:
        form = DocumentoEstagioForm(request.POST, request.FILES)
        if form.is_valid():
            novo_nome = form.renomear_arquivo(form.files['documento'].name)
            form.files['documento'].name = novo_nome
            DocumentoEstagioModel.objects.create(**form.cleaned_data)
            return render(request, 'arquivo_enviado_com_sucesso.html')
        else:
            context = {'form': form}
            return render(request, 'upload_documentos_estagio.html', context)


@area_company
def convenio_por_empresa(request):
    if request.method == 'GET':
        id_user = request.user.pk
        convenios = ConvenioModel.objects.filter(empresa_id=id_user)
        context = {'media_url': settings.MEDIA_URL,
                   'convenios': convenios}
        return render(request, 'convenio_por_empresa.html', context)
    else:
        return HttpResponseRedirect(r('core:core_index_empresa'))


@area_company
def estagiarios_por_empresa(request):
    if request.method == 'GET':
        id_user = request.user.pk
        convenios = DocumentoEstagioModel.objects.filter(
            empresa_id=id_user).order_by('-created_at')
        context = {'media_url': settings.MEDIA_URL,
                   'convenios': convenios}
        return render(request, 'estagiarios_por_empresa.html', context)
    else:
        return HttpResponseRedirect(r('core:core_index_empresa'))


@area_teacher
def listar_termos_compromisso_estagio(request):
    context = {'media_url': settings.MEDIA_URL}
    documentos = DocumentoEstagioModel.objects.termos_compromisso_estagio()
    context['tipo_documento'] = "Termo de compromisso de Estágio"
    context['documentos'] = documentos
    return render(request, 'listar_documentos.html', context)


@area_teacher
def listar_planos_de_atividades(request):
    context = {'media_url': settings.MEDIA_URL}
    documentos = DocumentoEstagioModel.objects.planos_de_atividades()
    context['tipo_documento'] = "Plano de Atividades"
    context['documentos'] = documentos
    return render(request, 'listar_documentos.html', context)


@area_teacher
def listar_termo_aditivo(request):
    context = {'media_url': settings.MEDIA_URL}
    documentos = DocumentoEstagioModel.objects.termos_aditivo()
    context['tipo_documento'] = "Termo Aditivo"
    context['documentos'] = documentos
    return render(request, 'listar_documentos.html', context)


@area_teacher
def listar_rescisao_de_contrato(request):
    context = {'media_url': settings.MEDIA_URL}
    documentos = DocumentoEstagioModel.objects.rescisao_de_contrato()
    context['tipo_documento'] = "Rescisão de Contrato"
    context['documentos'] = documentos
    return render(request, 'listar_documentos.html', context)


@area_teacher
def listar_ficha_avaliacao_estagiario(request):
    context = {'media_url': settings.MEDIA_URL}
    documentos = DocumentoEstagioModel.objects.ficha_avaliacao_estagiario()
    context['tipo_documento'] = "Ficha de avaliação do estagiário"
    context['documentos'] = documentos
    return render(request, 'listar_documentos.html', context)

@area_teacher
def listar_relatorio_parcial_estagio(request):
    context = {'media_url': settings.MEDIA_URL}
    documentos = DocumentoEstagioModel.objects.relatorio_parcial_estagio()
    context['tipo_documento'] = "Relatório Parcial do Estágio"

plataforma/estagio/templates/arquivo_enviado_com_sucesso.html
<{% extends "base.html" %}
{% load staticfiles %}
{% load static %}


{% block content %}

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    {% include "empresa_sidebar.html" %}
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        {% include "empresa_topbar.html" %}
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Envio de documentos</h1>
          </div>

            <form action={% url 'core:core_index_empresa' %} novalidate method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Envio de documentos realizado com sucesso.</div>
                <br>
                <center>
                <input type="submit" value="     OK     "/>
            </form>
        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

    {% include "rodape.html" %}

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>




{% endblock %}

plataforma/estagio/templates/pre_validar_documento_estagio.html
<{% extends "base.html" %}
{% load staticfiles %}
{% load static %}


{% block content %}

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    {% include "professor_sidebar.html" %}
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        {% include "professor_topbar.html" %}
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Aprovar Documentação de Estágio</h1>
          </div>

          <!-- Content Row -->
          <div class="row">

            <!-- Um card por convênio -->
             {% for documento in documentos %}
            <div class="col-xl-6 col-md-12 mb-4">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                        {{ documento.empresa.username }}
                      </div>
                      {{ documento.nome_aluno }}
                      <br>
                      {{ documento.nome_curso }}
                      <br>
                      {{ documento.tipo_de_documento }}

                      <form action={% url 'estagio:validar_documento_estagio' %} novalidate method="POST" enctype="multipart/form-data">
                          {% csrf_token %}
                          <input type='hidden' name='documento_id' value = "{{documento.pk }}"/>
                          <input type="submit" value="Emitir Parecer"/>
                          
                      </form>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">
                        <a href="{{media_url}}{{ documento.documento}}" target="_blank">Acessar Documento</a>
                      </div>
                    </div>
                  </div>

                </div>
              </div>
            </div>
            {% endfor %}


          </div>

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

    {% include "rodape.html" %}

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>




{% endblock %}

>

plataforma/estagio/templates/professor_upload_convenio.html
<{% extends "base.html" %}
{% load staticfiles %}
{% load static %}


{% block content %}

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    {% include "professor_sidebar.html" %}
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        {% include "professor_topbar.html" %}
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Upload - Convênio de Estágio</h1>
          </div>

          <!-- Content Row -->
          <div class="row">

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-6 col-md-12 mb-4">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <form action={% url 'estagio:professor_upload_convenio' %} novalidate method="POST" enctype="multipart/form-data">
                          {% csrf_token %}
                          
                          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{{form.empresa.label }}</div>
                          {{form.empresa }}
                          <br>
                          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{{form.documento.label }}</div>
                          <div class="h5 mb-0 font-weight-bold text-gray-800">
                          
                          {{form.documento }}
                          <br><br>
                          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{{form.validade.label }}</div>
                          {{form.validade }}
                          <br><br>
                          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{{form.observacao.label }}</div>
                          {{form.observacao }}
                          <br>
                          
                          <input type="submit" value="Upload "/>
                          
                      </form>
                      </div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>


          </div>

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

    {% include "rodape.html" %}

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>




{% endblock %}

>

plataforma/estagio/templates/professor_upload_documentos_estagio.html
<{% extends "base.html" %}
{% load staticfiles %}
{% load static %}


{% block content %}

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    {% include "professor_sidebar.html" %}
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        {% include "professor_topbar.html" %}
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Upload - Documentos de Estágio</h1>
          </div>

          <!-- Content Row -->
          <div class="row">

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-6 col-md-12 mb-4">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <form action={% url 'estagio:professor_upload_documentos_estagio' %} novalidate method="POST" enctype="multipart/form-data">
                          {% csrf_token %}
                          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{{form.nome_aluno.label }}</div>
                          {{form.nome_aluno }}
                          <br>
                          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{{form.empresa.label }}</div>
                          {{form.empresa }}
                          <br>
                          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{{form.documento.label }}</div>
                          <div class="h5 mb-0 font-weight-bold text-gray-800">
                          
                          {{form.documento }}
                          <br><br>
                          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{{form.tipo_documento.label }}</div>
                          {{form.tipo_documento }}
                          <br>
                          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{{form.curso_fatec.label }}</div>
                          {{form.curso_fatec }}
                          <br>
                          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{{form.observacao.label }}</div>
                          {{form.observacao }}
                          <br>
                          
                          <input type="submit" value="Upload "/>
                          
                      </form>
                      </div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>


          </div>

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

    {% include "rodape.html" %}

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>




{% endblock %}

>

plataforma/estagio/templates/upload_convenio.html
<{% extends "base.html" %}
{% load staticfiles %}
{% load static %}


{% block content %}

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    {% include "empresa_sidebar.html" %}
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        {% include "empresa_topbar.html" %}
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Upload - Convênio de Estágio</h1>
          </div>

          <!-- Content Row -->
          <div class="row">

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-6 col-md-12 mb-4">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <form action={% url 'estagio:upload_convenio' %} novalidate method="POST" enctype="multipart/form-data">
                          {% csrf_token %}
                          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{{form.documento.label }}</div>
                          <div class="h5 mb-0 font-weight-bold text-gray-800">
                          {{form.empresa }}
                          {{form.documento }}
                          <br><br>
                          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{{form.validade.label }}</div>
                          {{form.validade }}
                          <br><br>
                          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{{form.observacao.label }}</div>
                          {{form.observacao }}
                          <br>
                          
                          <input type="submit" value="Upload "/>
                          
                      </form>
                      </div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>


          </div>

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

    {% include "rodape.html" %}

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>




{% endblock %}

>

plataforma/estagio/templates/upload_documentos_estagio.html
<{% extends "base.html" %}
{% load staticfiles %}
{% load static %}


{% block content %}

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    {% include "empresa_sidebar.html" %}
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        {% include "empresa_topbar.html" %}
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Envio de documentos</h1>
          </div>

          <!-- Content Row -->
          <div class="row">
            <div class="col-xl-6 col-md-12 mb-4">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <form action={% url 'estagio:upload_documentos_estagio' %} novalidate method="POST" enctype="multipart/form-data">
                          {% csrf_token %}
                          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{{form.documento.label}}</div>
                          <div class="h5 mb-0 font-weight-bold text-gray-800">
                          {{form.empresa }}
                          {{form.documento }}
                          <br><br>
                          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{{form.nome_aluno.label}}</div>
                          {{form.nome_aluno }}
                          <br> 
                          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{{form.curso_fatec.label}}</div>
                          {{form.curso_fatec }}
                          <br>                          
                          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{{form.tipo_documento.label}}</div>
                          {{form.tipo_documento }}
                          <br>
                          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{{form.observacao.label}}</div>
                          {{form.observacao }}
                          <br>
                          
                          <input type="submit" value="Upload "/>
                          
                      </form>
                      </div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>


          </div>

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

    {% include "rodape.html" %}

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>




{% endblock %}