plataforma/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('quem_somos', views.equipe_fatec, name='quem_somos'),
]
urlpatterns_aluno = [
    path('index_aluno', views.index_aluno, name='core_index_aluno'),
    path('cadastro_novo_aluno', views.cadastro_novo_aluno, name='cadastro_novo_aluno'),
]

urlpatterns_professor = [
    path('index_professor', views.index_professor, name='core_index_professor'),
    path('perfil_professor', views.perfil_professor, name='perfil_professor'),
]
urlpatterns_empresa = [
    path('index_empresa', views.index_empresa, name='core_index_empresa'),
]
urlpatterns_manutencao = [
    path('index_manutencao', views.index_manutencao, name='core_index_manutencao'),
]
urlpatterns += urlpatterns_aluno
urlpatterns += urlpatterns_empresa
urlpatterns += urlpatterns_professor
urlpatterns += urlpatterns_manutencao

plataforma/estagio/urls.py
from django.urls import path
from . import views

app_name = 'estagio'

urlpatterns = []

urlpatterns_empresa = [
    path('upload_convenio', views.upload_convenio,
         name='upload_convenio'),
    path('upload_documentos_estagio', views.upload_documentos_estagio,
         name='upload_documentos_estagio'),
    path('convenio_por_empresa', views.convenio_por_empresa,
         name='convenio_por_empresa'),
    path('estagiarios_por_empresa', views.estagiarios_por_empresa,
         name='estagiarios_por_empresa'),
]
urlpatterns_professor = [
     path('professor_upload_documentos_estagio',
         views.professor_upload_documentos_estagio,
         name='professor_upload_documentos_estagio'),
     path('professor_upload_convenio', views.professor_upload_convenio,
         name='professor_upload_convenio'),
     path('pre_validar_convenio', views.pre_validar_convenio,
         name='pre_validar_convenio'),
     path('validar_convenio', views.validar_convenio,
         name='validar_convenio'),
     path('pos_validar_convenio', views.pos_validar_convenio,
         name='pos_validar_convenio'),
     path('listar_todos_convenios', views.listar_todos_convenios,
         name='listar_todos_convenios'),
     path('pre_validar_documento_estagio', views.pre_validar_documento_estagio,
         name='pre_validar_documento_estagio'),
     path('validar_documento_estagio', views.validar_documento_estagio,
         name='validar_documento_estagio'),
     path('pos_validar_documento_estagio', views.pos_validar_documento_estagio,
         name='pos_validar_documento_estagio'),
     path('listar_termos_compromisso_estagio',
          views.listar_termos_compromisso_estagio,
         name='listar_termos_compromisso_estagio'),
     path('listar_planos_de_atividades', views.listar_planos_de_atividades,
         name='listar_planos_de_atividades'),
     path('listar_termo_aditivo', views.listar_termo_aditivo,
         name='listar_termo_aditivo'),
     path('listar_rescisao_de_contrato', views.listar_rescisao_de_contrato,
         name='listar_rescisao_de_contrato'),
     path('listar_ficha_avaliacao_estagiario', views.listar_ficha_avaliacao_estagiario,
         name='listar_ficha_avaliacao_estagiario'),
     path('listar_relatorio_parcial_estagio', views.listar_relatorio_parcial_estagio,
         name='listar_relatorio_parcial_estagio'),
     path('listar_relatorio_final_estagio', views.listar_relatorio_final_estagio,
         name='listar_relatorio_final_estagio'),
]
urlpatterns += urlpatterns_empresa
urlpatterns += urlpatterns_professor

plataforma/manutencao/urls.py
from django.urls import path
from . import views

app_name = 'manutencao'

urlpatterns = []

urlpatterns_empresa = [
    path('cadastro_empresa', views.cadastro_empresa,
         name='cadastro_empresa'),

]
urlpatterns_professor = [
    path('cadastro_professor', views.cadastro_professor,
         name='cadastro_professor'),
]
urlpatterns_aluno = [
    path('cadastro_aluno', views.cadastro_aluno,
         name='cadastro_aluno'),
]
urlpatterns_editar = [
        path('editar_usuario', views.editar_usuarios,
         name='editar_usuario'),
]
urlpatterns += urlpatterns_empresa
urlpatterns += urlpatterns_professor
urlpatterns += urlpatterns_aluno
urlpatterns += urlpatterns_editar

plataforma/plataforma/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from plataforma import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('vitrine.urls')),
    path('manutencao/', include('manutencao.urls')),
    path('estagio/', include('estagio.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plataforma/core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

CURSO_FATEC = (
    ('0', 'Sistemas para Internet'),
    ('1', 'Gestão Empresarial'),
)


class User(AbstractUser):
    is_student = models.BooleanField(verbose_name='Estudante', default=False)
    is_teacher = models.BooleanField(verbose_name='Professor', default=False)
    is_trainee_coordinator = models.BooleanField(
        verbose_name='Coodenador de Estágio', default=False)
    is_company = models.BooleanField(verbose_name='Empresa', default=False)

    def __str__(self):
        if self.first_name == '':
            return self.email
        return self.first_name + ' ' + self.last_name

    class Meta:
        verbose_name_plural = 'Usuários'
        verbose_name = 'Usuário'
        ordering=('first_name','email')

plataforma/core/forms.py
from django import forms
from django.forms import ModelForm
from core.models import User
from django.core.exceptions import ValidationError


class CadastroNovoAlunoForm(ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password')
        labels = {
            'first_name': 'Nome:',
            'last_name': 'Sobrenome:',
            'username': 'E-mail institucional:',
            'password': 'Senha:',
        }
        widgets = {
            'first_name': forms.TextInput(),
            'last_name': forms.TextInput(),
            'username': forms.EmailInput(),
            'password': forms.PasswordInput(),
        }
        error_messages = {
            'username': {
                'required': ("Informe o e-mail."),
            },
            'first_name': {
                'required': ("Informe seu nome."),
            },
            'last_name': {
                'required': ("Informe seu sobrenome."),
            }
        }

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if first_name == '':
            raise ValidationError(
                'Informe seu nome.')
        return self.cleaned_data['first_name']

    def clean_username(self):
        username = self.cleaned_data['username']
        if not username.endswith('@fatec.sp.gov.br'):
            raise ValidationError('Informe seu e-mail institucional.')
        return self.cleaned_data['username']

    def clean_password(self):
        senha = self.cleaned_data['password']
        possui_numeros = False
        for n in list('1234567890'):
            if n in list(senha):
                possui_numeros = True
        if not possui_numeros:
            raise ValidationError(
                'A senha precisa ter pelo menos um número.')
        if len(senha) < 8:
            raise ValidationError(
                'A senha precisa ter pelo menos 8 caracteres.')
        return self.cleaned_data['password']

plataforma/core/views.py
from django.contrib.auth import logout as auth_logout
from django.shortcuts import redirect, render
from core.decorators import (area_student, area_teacher,
                             area_company, area_admin)
from core.functions import auth_request, register_student, authenticate
from django.contrib.auth.decorators import login_required
from core.forms import CadastroNovoAlunoForm


def login(request):
    if request.method == "GET":
        return render(request, 'login.html')
    else:
        if auth_request(request):
            return redirect('core:home')
        else:
            return redirect('core:login')


def logout(request):
    auth_logout(request)
    return render(request, 'login.html')


@login_required
def home(request):
    context = {'user': request.user}
    return render(request, 'index.html', context)


@area_student
def index_aluno(request):
    context = {}
    return render(request, 'aluno_index.html', context)


@area_teacher
def index_professor(request):
    context = {}
    return render(request, 'professor_index.html', context)


@area_teacher
def perfil_professor(request):
    context = {}
    return render(request, 'professor_mudar_perfil.html', context)


@area_company
def index_empresa(request):
    context = {}
    return render(request, 'empresa_index.html', context)


@area_admin
def index_manutencao(request):
    context = {}
    return render(request, 'manutencao_index.html', context)


def equipe_fatec(request):
    context = {}
    return render(request, 'equipe_fatec.html', context)


def cadastro_novo_aluno(request):
    if request.method == 'GET':
        context = {'form': CadastroNovoAlunoForm()}
        return render(request, 'cadastro_novo_aluno.html', context)
    else:
        form = CadastroNovoAlunoForm(request.POST)
        if form.is_valid():
            register_student(**form.cleaned_data)
            return redirect('core:login')
        else:
            context = {'form': form}
            return render(request, 'cadastro_novo_aluno.html', context)

plataforma/core/templates/empresa_index.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}


{% block content %}

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    {% include "empresa_sidebar.html" %}
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        {% include "empresa_topbar.html" %}
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Plataforma FATEC - Módulo Empresa</h1>
          </div>



        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

    {% include "rodape.html" %}

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>




{% endblock %}

plataforma/core/templates/empresa_sidebar.html
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'core:home' %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Módulo Empresa</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:core_index_empresa' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Painel de Controle</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Estágio
      </div>

      <!-- Nav Item - Convênio de Estágio -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-cog"></i>
          <span>Convênio</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Termo de Convênio</h6>
              <a class="collapse-item" href="{% url 'estagio:convenio_por_empresa' %}">Convênios</a>
              <a class="collapse-item" href="{% url 'estagio:upload_convenio' %}">Upload</a>
          </div>
        </div>
      </li>

      <!-- Nav Item - Estagiários -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-fw fa-wrench"></i>
          <span>Estagiários</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Documentos:</h6>
            <a class="collapse-item" href="{% url 'estagio:estagiarios_por_empresa' %}">Estagiários</a>
            <a class="collapse-item" href="{% url 'estagio:upload_documentos_estagio' %}">Upload</a>
          </div>
        </div>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Equipe FATEC
      </div>

      <!-- Nav Item - Tables -->
      <li class="nav-item">
        <a href="{% url 'core:quem_somos' %}"
        class="nav-link" href="tables.html">
          <i class="fas fa-fw fa-table"></i>
          <span>Quem somos</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

plataforma/core/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}


{% block content %}

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Begin Page Content -->
        <div class="container-fluid">
        <br>
          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Plataforma FATEC Araras</h1>
            <h3 class="h6 mb-0 text-gray-800">{{user}}</h3>
            <a href="{% url 'core:logout' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-sm text-white-50"></i> Logout</a>
          </div>
          <br>

          <!-- Content Row -->
          <div class="row">

            <!-- Módulo Aluno -->
            <div class="col-xl-3 col-md-6 mb-4">
            <a href="{% url 'core:core_index_aluno' %}">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Aluno</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">Módulo Aluno</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </a>  
            </div>

            <!-- Módulo Professor  -->
            <div class="col-xl-3 col-md-6 mb-4">
            <a href="{% url 'core:core_index_professor' %}">
              <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Professor</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">Módulo Professor</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-comments fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </a>
            </div>

            <!--  Módulo Empresa -->
            <div class="col-xl-3 col-md-6 mb-4">
            <a href="{% url 'core:core_index_empresa' %}">
              <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Empresa</div>
                      <div class="row no-gutters align-items-center">
                        <div class="col-auto">
                          <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">Módulo Empresa</div>
                        </div>
                      </div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
              </a>
            </div>
          

            <!--  Módulo Administrativo -->
            <div class="col-xl-3 col-md-6 mb-4">
            <a href="{% url 'core:core_index_manutencao' %}">
              <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Manutenção</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">Módulo Manutenção</div>
                    </div>
                    <div class="col-auto">
                      
                    </div>
                  </div>
                </div>
              </div>
            </a>
            </div>
          </div>
        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

    {% include "rodape.html" %}

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>




{% endblock %}

plataforma/core/templates/manutencao_sidebar.html
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'core:home' %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Módulo Manutenção</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:core_index_manutencao' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Painel de Controle</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Cadastros
      </div>

      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseEmpresa" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-cog"></i>
          <span>Empresa</span>
        </a>
        <div id="collapseEmpresa" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
              <a class="collapse-item" href="{% url 'manutencao:cadastro_empresa' %}">Cadastrar</a>
          </div>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseProfessor" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-fw fa-wrench"></i>
          <span>Professor</span>
        </a>
        <div id="collapseProfessor" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="{% url 'manutencao:cadastro_professor' %}">Cadastrar</a>
          </div>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseAlunos" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-fw fa-wrench"></i>
          <span>Aluno</span>
        </a>
        <div id="collapseAlunos" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="{% url 'manutencao:cadastro_aluno' %}">Cadastrar</a>
          </div>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseEditarUsuario" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-cog"></i>
          <span>Editar</span>
        </a>
        <div id="collapseEditarUsuario" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
              <a class="collapse-item" href="{% url 'manutencao:editar_usuario' %}">Usuários</a>
          </div>
        </div>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Futuras funcionalidades
      </div>

      <!-- Nav Item - Tables -->
      <li class="nav-item">
        <a href="#"
        class="nav-link" href="tables.html">
          <i class="fas fa-fw fa-table"></i>
          <span>--</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

plataforma/core/templates/professor_sidebar.html
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'core:home' %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Módulo Professor</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:home' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Painel de Controle</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Estágio
      </div>

      <!-- Nav Item - Convênio de Estágio -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-cog"></i>
          <span>Convênio</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Termo de Convênio</h6>
            <a class="collapse-item" href="{% url 'estagio:professor_upload_convenio' %}">Enviar Termo</a>
              <a class="collapse-item" href="{% url 'estagio:pre_validar_convenio' %}">Aprovar</a>
              <a class="collapse-item" href="{% url 'estagio:listar_todos_convenios' %}">Listar</a>
          </div>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#documentos_estagiarios" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-fw fa-folder"></i>
          <span>Estagiários</span>
        </a>
      <div id="documentos_estagiarios" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
          <h6 class="collapse-header">Documentos:</h6>
            <a class="collapse-item" href="{% url 'estagio:listar_termos_compromisso_estagio' %}">Termo de compromisso</a>
            <a class="collapse-item" href="{% url 'estagio:listar_planos_de_atividades' %}">Plano de Atividades</a>
            <a class="collapse-item" href="{% url 'estagio:listar_termo_aditivo' %}">Termo aditivo</a>
            <a class="collapse-item" href="{% url 'estagio:listar_rescisao_de_contrato' %}">Rescisão de Contrato</a>
            <a class="collapse-item" href="{% url 'estagio:listar_ficha_avaliacao_estagiario' %}">Ficha de avaliação</a>
            <a class="collapse-item" href="{% url 'estagio:listar_relatorio_parcial_estagio' %}">Relatório Parcial</a>
            <a class="collapse-item" href="{% url 'estagio:listar_relatorio_final_estagio' %}">Relatório Final</a>              
        </div>
      </div>

      <!-- Nav Item - Estagiários -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#envio_docs_estagiarios" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-fw fa-folder"></i>
          <span>Documentos</span>
        </a>
        <div id="envio_docs_estagiarios" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Envio:</h6>
              <a class="collapse-item" href="{% url 'estagio:professor_upload_documentos_estagio' %}">Envio de documentos</a>
              <a class="collapse-item" href="{% url 'estagio:pre_validar_documento_estagio' %}">Aprovar Documentação</a>
          </div>
        </div>


      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Novas funcionalidades
      </div>

      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#configuracao" aria-expanded="true" aria-controls="collapsePages">
          <i class="fas fa-fw fa-folder"></i>
          <span>Futuras funcionalidades</span>
        </a>
        <div id="configuracao" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Painel:</h6>
            <a class="collapse-item" href="">to-do</a>
            <div class="collapse-divider"></div>
            <h6 class="collapse-header">Painel 2:</h6>
            <a class="collapse-item" href="">to-do</a>
          </div>
        </div>
      </li>



      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

plataforma/core/templates/rodape.html
      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Feito com &hearts; pelos professores da FATEC Araras</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->